# Themes (onedark or nord)
export TMUX_THEME="onedark"
export NVIM_THEME="onedark"
export STARSHIP_THEME="onedark"
export WEZTERM_THEME="onedark"

# Use Neovim as default editor
export EDITOR="nvim"
export VISUAL="nvim"
