# Themes (onedark or nord)
export TMUX_THEME="nord"
export NVIM_THEME="nord"
export STARSHIP_THEME="nord"
export WEZTERM_THEME="nord"

# Use Neovim as default editor
export EDITOR="nvim"
export VISUAL="nvim"
